### ISSUE TITLE
Camunda platform error (forms-flow-bpm)

### ISSUE THREAD

**Issue by edlynvillegas** [AOT-Technologies/forms-flow-ai#1018]
### Please provide information about your setup

- formsflow.ai Version: 5.0.1
- Browser: Brave
- Browser version: 1.45.118

### Steps to Reproduce

Installation steps from Docker-based Installation > Individual Service Deployment > [forms-flow-bpm](https://aot-technologies.github.io/forms-flow-ai-doc/formsflow_bpm.html)

The same issue was encountered with Docker-based Installation > [Quick Installation](https://aot-technologies.github.io/forms-flow-ai-doc/index.html)

### Observed Behaviour

![image](https://user-images.githubusercontent.com/39414627/203723447-eb0ea3db-88ae-4511-b579-caf916d2e9e5.png)
![image](https://user-images.githubusercontent.com/39414627/203724132-568b62d2-98b9-4254-9546-b3691f87e069.png)

![image](https://user-images.githubusercontent.com/39414627/203719677-3c73da7f-8eaa-477a-b5a0-4a47de49c059.png)

### Expected Behaviour

Same with this
![image](https://user-images.githubusercontent.com/39414627/203720629-dcfee3ee-196f-452d-86d9-5188783c6820.png)

**Comment by sumesh-aot** [comment]
@alanraju-aot Can you please check this ?

**Comment by alanraju-aot** [comment]
👍

**Comment by alanraju-aot** [comment]
Observed issues:
1. Keycloak configuration not done properly.
2. IP address may be different, may be using wsl Ip(Please confirm that).
3. Check the webapi loggs too.

**Comment by maddin79** [comment]
@alanraju-aot The question states that this is also in the quick install setup. I tested it and have the same error. It seems in your quick install script is an error. We can not test the application. Furthermore, if I apply for the test account on your web page, I never get an email. Makes it impossible to have a quick look at your app. 

Best
Martin

**Comment by sumesh-aot** [comment]
@maddin79 have you tried submitting request at https://formsflow.ai/try-it-now/. If you haven't received any email with credentials after submitting request, please send an email to sumesh.pk@aot-technologies.com with details on email address you have provided for sandbox access.

**Comment by sumesh-aot** [comment]
@maddin79 @edlynvillegas 
Can you please check if there are any other application running on 8080? It looks like keycloak didn't come up in this case, which is preventing BPM startup. If you are still unable to bring it up, please send an email to above address so that we connect and screen share to resolve the issue.

**Comment by maddin79** [comment]
@sumesh-aot Thanks for the reply. I do not have anything running on port 8080. If would be a different error if I would have. 
I'll send you an email with the address information.

**Comment by sreehari-aot** [comment]
Closing this issue since the quick install scripts are updated.
