### ISSUE TITLE
How to access camunda rest api from another application?

### ISSUE THREAD

**Issue by uzrnem** [AOT-Technologies/forms-flow-ai#1073]
we have created a extrernal task which would connect to camunda engine-rest api, but its giving 401 unauthorized error. Currently, camunda rest apis are only getting accessed through form-flow-ai web ui.

**Comment by abhilash-aot** [comment]
@uzrnem Can you give any code snippets or error logs. The camunda rest apis would need to generate and send the keycloak token for getting access.

**Comment by uzrnem** [comment]
Its working as there was typo in rest api documentation of camunda
