### ISSUE TITLE
Is there any way we can publish form to a particular client instead of all?

### ISSUE THREAD

**Issue by sreehari-aot** [AOT-Technologies/forms-flow-ai#1164]

**Comment by auslin-aot** [comment]
We can publish forms for a specific client by creating a separate workflow for the client group.

The following steps describe how forms are published specifically for the user group.

1 . In keycloak, create separate client groups.
![image](https://user-images.githubusercontent.com/99173163/213185358-4fbb8755-9c2e-433c-ada8-03a341dd597d.png)

2. Assign the client groups to the client role.
![image](https://user-images.githubusercontent.com/99173163/213186104-402cc21c-0ceb-4471-8a01-f079ccbf68f0.png)

3. Create users and assign them to the client group.
![image](https://user-images.githubusercontent.com/99173163/213186424-ff89f183-9097-48b0-a60c-a9835f9d3bca.png)

4. Create separate workflows for each group and associate them with the forms. Here the client1 group “demoapproval” workflow is associated with the “demoform” form.
![image](https://user-images.githubusercontent.com/99173163/213186622-547fc135-3f53-4ddf-b33c-ddafdd1cab9f.png)

The client2 group “onestepapproval” workflow is associated with the “demoform2” form.
![image](https://user-images.githubusercontent.com/99173163/213188238-dfdb6d6e-81a7-4b4f-be13-c1b0d30f5567.png)

5. Login in camunda, goto admin -> Manage Authorizations
![image](https://user-images.githubusercontent.com/99173163/213186835-5bfcb584-93ed-4be4-ba1e-8eddf290bc84.png)


6. In Process Definition, add the specific client group and workflow key. Here demoapproval key is added to the client1 group. So client1 users can see forms that are associated with the demoapproval workflow. If users of the specific group need to see forms of another workflow, then add that as a new row/entry in addition to the existing one.
![image](https://user-images.githubusercontent.com/99173163/213187005-e230d279-ba27-4ffa-9dfe-9c41a8b08f6b.png)

7. Add the client groups to the “Process Instance Authorizations” section too with resource id “*”. To give create instance permission to the group.
 
![image](https://user-images.githubusercontent.com/99173163/213187161-f7314ab0-0cfa-4106-a4f4-705ed5a3b3a5.png)

8.  Add the client groups to the “Authorization” section.
![image](https://user-images.githubusercontent.com/99173163/213187300-e5402c70-c4c6-4028-85c4-39ed30f2abb1.png)


9. Now log in as a client1 user, only forms with the “demoapproval” workflow are visible for them.
![image](https://user-images.githubusercontent.com/99173163/213187448-786ebe98-9e19-495a-baa4-b655c9ed76ab.png)

client2 group users can view only forms with the “onestepapproval” workflow.
![image](https://user-images.githubusercontent.com/99173163/213187553-698e3f4b-53cb-4866-bc32-305203a2d9d9.png)

**Comment by sreehari-aot** [comment]
Thanks, @auslin-aot

**Comment by sumesh-aot** [comment]
@sreehari-aot @auslin-aot we can move this to Q&A (https://github.com/AOT-Technologies/forms-flow-ai/discussions/categories/q-a). I have enabled this earlier, for these kind of discussions and Q&A.

**Comment by sreehari-aot** [comment]
sure @sumesh-aot

**Comment by sreehari-aot** [comment]
closing since the issue is moved to discussions.
