### ISSUE TITLE
When using FormConnectorListener, why values from previous forms submited not appear in the second form?

### ISSUE THREAD

**Issue by abhishekbeesony** [AOT-Technologies/forms-flow-ai#117]
Hello All, 

I was try to use the formconnectorListener. Client submit forms with fields name , age and address. Now when Reviewer claims it , there is a second forms that display for the reviewer(internal form) which has fields name , age , address and COMMENTS.

So when the review claim , the name , age and address should automatically appear in the second forms and reviewer should only add his comments. 

IS this the way that should work? Please suggest. 

Thank you.

**Comment by abhilash-aot** [comment]
@abhishekbeesony You would have to customize/ add a new listener to achieve this. The current example doesn't fill for the next form. You could see the previous form in history in that particular example. We will be coming up with a new example/workflow in our next Release.  You would need to edit the workflow as per your business logic. Please contact support@aot-technologies.com/info@formsflow.ai for having a discussion and define future collaborations. Thanks.
