### ISSUE TITLE
Fail to install Analytics Engine following the instructions

### ISSUE THREAD

**Issue by EricRossC** [AOT-Technologies/forms-flow-ai#119]
### Please provide information about your setup

- formsflow.ai Version: RC4.0.0
- Browser:  Chrome
- Browser version: Latest

### Steps to Reproduce

0. Create a new VM and install a fresh copy of Rocky Linux 8.4
1. Follow the steps in https://github.com/AOT-Technologies/forms-flow-ai/tree/master/deployment/docker
2. Follow Keycloak steps in https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-idm/keycloak/README.md (Everything OK)
3. Follow forms-flow-analytics steps in https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-analytics/README.md
4.  In "Running the application" https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-analytics/README.md#running-the-application
5. Running "docker-compose -f docker-compose-linux.yml run --rm server create_db" works OK
6. Running "docker-compose -f docker-compose-linux.yml up -d" fails

### Observed Behaviour

    # docker-compose -f docker-compose-linux.yml up -d
    Building adhoc_worker
    unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: /usr/libexec/git-core/git-remote-https: /tmp/_MEIGDn5IA/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /lib64/libcurl.so.4)
    /usr/libexec/git-core/git-remote-https: /tmp/_MEIGDn5IA/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /lib64/libssh.so.4)
    /usr/libexec/git-core/git-remote-https: /tmp/_MEIGDn5IA/libcrypto.so.1.1: version `OPENSSL_1_1_1b' not found (required by /lib64/libssh.so.4)
    /usr/libexec/git-core/git-remote-https: /tmp/_MEIGDn5IA/libcrypto.so.1.1: version `OPENSSL_1_1_1b' not found (required by /lib64/libk5crypto.so.3)
    : signal: broken pipe
    ERROR: Service 'adhoc_worker' failed to build : Build failed

### Expected Behaviour

It should start so we can continue with the next step (forms-flow-forms Setup)

**Comment by abhilash-aot** [comment]
@EricRossC  We will check and update you on that issue. Meanwhile, you can ignore that step and continue with other steps keeping the default values for analytics.

**Comment by abhilash-aot** [comment]
Updated Analytics installation in https://github.com/AOT-Technologies/forms-flow-ai/releases/tag/v4.0.1 . Please Check.
