### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by xalcolm1** [AOT-Technologies/forms-flow-ai#1246]
I've been trying to figure out how to setup the file upload component for the forms, is this something that you have figured out how to do?

**Comment by Josephalexantony-aot** [comment]
Hi @xalcolm1 we are interested to know how did you tried out the file upload component. 
The file upload component is premium in form.io. We have created a custom componet for file upload. you can configure it with your db. 
https://github.com/AOT-Technologies/forms-flow-ai-examples/tree/main/custom-components/custom-file-upload

**Comment by xalcolm1** [comment]
Hey @Josephalexantony-aot
Thanks for pointing me to your file upload component! 
As for my approach: I tried to set up minio using a tutorial from form.io. Apparently there are more options  accessible in the enterprise version. I tried to look for some variables that I might be able to change in the repository but couldn't find anything.
