### ISSUE TITLE
Save and Review Button  - users are confused

### ISSUE THREAD

**Issue by matthewhall78** [AOT-Technologies/forms-flow-ai#14]
The drone PIA business users are reporting that users are looking for a Submit button.
Can you consider changing the label of the button to "Submit"?

**Comment by sumathi-thirumani-aot** [comment]
Change Details/Solution : Login into application with designer role and change the label name to "Submit".
Action: Implemented in production.

**Comment by sumathi-thirumani-aot** [comment]
> 
> 
> The drone PIA business users are reporting that users are looking for a Submit button.
> Can you consider changing the label of the button to "Submit"?
