### ISSUE TITLE
Enable to see the submitted form in tasklist at camunda side and in reviewer side as well.

### ISSUE THREAD

**Issue by Soniyasharma6868** [AOT-Technologies/forms-flow-ai#1473]
### Discussed in https://github.com/AOT-Technologies/forms-flow-ai/discussions/1472

<div type='discussions-op-text'>

<sup>Originally posted by **Soniyasharma6868** June 28, 2023</sup>
Hello Gentlemen,

I am creating simple submission form. And I created a filter in Camunda side as well. Added the task-listener for the work-flow. But after submitting the form . Submitted form not able to see in the task-list.  All yours support appreciable.Thanks in advance:) </div>

**Comment by abhilash-aot** [comment]
@Soniyasharma6868  Could you please provide additional information or screenshots? The screenshot uploaded in #1472 appears to be incorrect. Can you verify if the workflow has been correctly added to the form design, including a user task? The default workflow in formsflow.ai only includes a service task.
![image](https://github.com/AOT-Technologies/forms-flow-ai/assets/61222674/ee15f107-bcbb-4b95-b4f1-2e29f674aaf7)
