### ISSUE TITLE
how to redirect one form to another form based on the result of workflow process?

### ISSUE THREAD

**Issue by man-chi** [AOT-Technologies/forms-flow-ai#152]
currently, the implementation will be like the following: form-1 -> submit form-1 -> execute process-A  (unable to notify the frontend on the process result)

however, we would like to build multiple form wizard with workflow engine like this: form-1 -> submit form-1 -> execute process-A -> based on the conditional result of process-A, if true then display form-2, else if false then display form-3

kindly advise on how to perform this logic.

some thoughts: in the form-1 submit button -> select submit = "custom" -> define custom logic -> use javascript to call camunda rest api polling to check the response of process instance, process instance will be set with "action" on next step, such as "step-2" or "step-3" based on the condition of the process completion. then redirect user using javacript. 

another thought with more effort: building Single Page Application (with Wizard) then create websocket to listen call back from workflow upon process completion? 

-please advise

**Comment by shibin-aot** [comment]
To associate redirect form, you can use camunda's task extensions.
You can add the property formName (Name) and {formName from form.io} (Value) as extension property, doing this will add the New formName as external property.   eg: Key : formName, Value : createNewBusinessLicenseApplication

To complete the association you also have to add FormConnectorListener in the Task Listener of camunda workflow. (You can refer - https://github.com/AOT-Technologies/forms-flow-ai/tree/master/forms-flow-bpm/starter-examples/listeners  to know how to use external listeners in formsflow.ai bpmn).

I really appreciate your thoughts and ideas. Let us know if you need more clarity on this.

**Comment by man-chi** [comment]
@shibin-aot thanks for your prompt reply. is the FormConnectorListener calling back to the form.io by websocket? does it work on the form.io wizard feature as well?

**Comment by shibin-aot** [comment]
No with FormConnectorListener you can only associate a new form with a task of an existing workflow.
The new form will show in the RHS of the task on click

**Comment by Preethamkv** [comment]
@shibin-aot We tried adding the FormConnectorListener in the Task Listener of Camunda workflow as mentioned in the reference document. But the redirection is not working, not sure what are we missing here. 
Also, will it redirect to the new form on form submit (OR) will be shown as Task in the task list?

**Comment by shibin-aot** [comment]
It will be shown as a Task in the Task list.

**Comment by man-chi** [comment]
@shibin-aot may I know what is the setting & configuration required on the form.io(form designer) in order to handle the listener?  then perform redirection on the UI?
e.g. form-1 submission -> workflow with formconnectorlistener -> do validation check -> if true -> redirect user to form2 , if false  -> redirect user to form3 . do we need to configure any setting in form1, form2 or form3 , in order to do that?

please help

**Comment by shibin-aot** [comment]
No 👍 . Only workflow changes are sufficient

**Comment by Preethamkv** [comment]
@shibin-aot After debuging the problem got to know that process associated with form is not initializing when the Task-Listener has added to the process workflow. Is there any config to be added? Attached the workflow we are using. Please let us know if u need any other details.
<img width="1413" alt="Screenshot 2021-09-30 at 8 05 28 PM" src="https://user-images.githubusercontent.com/35090978/135476063-a036105b-4d7a-4d9a-bfbc-65bd85800794.png">

**Comment by shibin-aot** [comment]
Please make sure that you added the extension correctly, also the input fields.
![extention](https://user-images.githubusercontent.com/83489861/135574284-c9869b04-8de1-40df-a621-52483c3d710d.PNG)
![input](https://user-images.githubusercontent.com/83489861/135574319-1ba0374f-d3c9-429e-8239-b2b1a11c4f42.PNG)

**Comment by shibin-aot** [comment]
Hope the steps are clear for you, if you further face any issues please let us know. I will close this issue for now.
