### ISSUE TITLE
Issue with 400 Bad Request Error on form.io service

### ISSUE THREAD

**Issue by brianli-md** [AOT-Technologies/forms-flow-ai#1523]
### Please provide information about your setup

- formsflow.ai Version: 5.1.1
- Browser: Brave
- Browser version: [Version 1.52.130 Chromium: 114.0.5735.198 (Official Build) (arm64)](https://brave.com/latest/)

### Steps to Reproduce

I encountered while using the FormsFlow AI repository. I cloned the repository from the following URL: [https://github.com/AOT-Technologies/forms-flow-ai], specifically using the branch 5.1.1.

The problem arises when I attempt to interact with the form.io service by clicking on a task. At that point, I receive a "400 Bad Request" error. The request URL triggering the error is [https://f.3dollarbid.com/current].

I am using the "formsflow-clerk" account while encountering this issue.

### Observed Behaviour

It seems that the error is related to the following message received in the response:
{
    "status": 400,
    "message": "Cast to ObjectId failed for value \"formsflow-clerk@aot-technologies.com\" (type string) at path \"_id\" for model \"submission\""
}
![WhatsApp Image 2023-07-11 at 5 25 11 PM](https://github.com/AOT-Technologies/forms-flow-ai/assets/139221375/574adebb-0823-421f-9174-e73eab4617cc)
![WhatsApp Image 2023-07-11 at 5 25 26 PM](https://github.com/AOT-Technologies/forms-flow-ai/assets/139221375/0c158be2-9ff7-4145-a4ce-5e0f8e5a7d73)

### Expected Behaviour

A 200 response

I kindly seek for your assistance in resolving this problem. It would be greatly appreciated if you could investigate the cause of the "400 Bad Request" error and suggest a solution. Any guidance or instructions you can provide to help me overcome this issue would be invaluable.

**Comment by brianli-md** [comment]
When I request /current api (formio API), the content of the JWT token that sent along with it is strange, the user._id field is email from keycloak.

The decoded JWT payload: 
```
{
  "external": true,
  "form": {
    "_id": "64ad7c5e878ef3e36b9d6456"
  },
  "user": {
    "_id": "formsflow-clerk@aot-technologies.com",
    "roles": [
      "64ad7c5e878ef3e36b9d6447"
    ]
  },
  "iat": 1689153408,
  "exp": 1689167808
}
```

I tried to login into the mongodb container, and accessed the mongo db, then I saw the "submissions" table only takes ObjectId, not emails. if this the reason of 401 error, and any solution to fix it? Thanks!

**Comment by abhilash-aot** [comment]
You can ignore that Particular Error. The current endpoint checks for users in the formio database, which we are not utilizing for user management. Our user data is exclusively stored in Keycloak. For more information, please refer to the duplicated error and response available here: https://github.com/AOT-Technologies/forms-flow-ai/issues/106
