### ISSUE TITLE
Form access get reset in Form.io dashboard

### ISSUE THREAD

**Issue by DivyaKMenon** [AOT-Technologies/forms-flow-ai#165]
We have set up the public route and anonymous form submission. As AOT team suggested, we have setup access permission for the anonymous user in the form.io dashboard(3001). The problem we are facing is that, once we set the roles for "Create Own Submission", and after making a certain number of submit requests from the web, the roles get reset to default config and we will have to do the setup again. This happened quite a few times. Can you please suggest what can be done or if we can debug the issue from logs?

**Comment by abhilash-aot** [comment]
Hi @DivyaKMenon and @man-chi ,
We have implemented the forms Anonymous feature and pushed to v4.0.5-alpha branch as of now. You can refer that or use that branch for getting this functionality. We have added changes to UI/ Api layer to accomodate this change. Thanks.

An option is added at the Design of form to achieve this. 

![image](https://user-images.githubusercontent.com/61222674/154647956-84c6afd8-21e2-479e-807e-d9f2b5643dd7.png)

Anonymous public form url can be copied and used to send to client or open in other browser ,
![image](https://user-images.githubusercontent.com/61222674/154648220-48a55a88-59bf-435e-bd99-f0137b6f293b.png)

Note- forms that are made anonymous and public will only appear publicaly.

![image](https://user-images.githubusercontent.com/61222674/154648392-58ca9943-4ea4-463e-9cb9-0470958941a6.png)
