### ISSUE TITLE
Incorrect URL getting called for KeyCloak

### ISSUE THREAD

**Issue by siva-krishna-m** [AOT-Technologies/forms-flow-ai#182]
I have followed the istructions and have installed the complete modules. While trying to run the FormsFlow Web on port 3000, I see that the following call in netwrk tab is failing. can you please guide on this. I see there is some duplication in the URL, but this is captured as is from the Network Tab

http://localhost:3000/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/undefined/auth/realms/forms-flow-ai/protocol/openid-connect/auth?client_id=forms-flow-web&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fsilent-check-sso.html&state=dfe26be0-4d2d-42e7-851d-dc7c8931bf2b&response_mode=fragment&response_type=code&scope=openid&nonce=1718a836-c8a8-4e1f-87c1-793ce7e64a6b&prompt=none&code_challenge=pB7xh06Qyq1ZwIvslCrW3AON11Su_5B4sdFantXY0RM&code_challenge_method=S256

**Comment by abhilash-aot** [comment]
Can you share the Env of keycloak you have added. Seems Env for keycloak is missing

**Comment by siva-krishna-m** [comment]
I used command 'docker-compose up --build -d' in forms-flow-web and its working fine
