### ISSUE TITLE
 Formsflow External Access

### ISSUE THREAD

**Issue by danielwebart** [AOT-Technologies/forms-flow-ai#2039]
Hello, we installed formsflow in a local Windows 11 environment with Docker Desktop 4.29.0. It's working fine for local access, but we need to access it externally. We redirected port 3000 on the firewall, pointing to the internal IP where Docker is installed, but when calling the external ip url:3000, the forms login screen appears and when entering the username and password to access, the error occurs timeout, appearing to be a redirection problem between ports 3000 and 8080 (forms/keycloak). Has anyone ever had to grant access to forms in a similar scenario and do you have any tips? Thank you very much.

**Comment by kiran-aot** [comment]
Hi @danielwebart

- Is the container port the same as the external port, i.e., are both set to 3000?
- Check your firewall rules again to ensure that there are no restrictions or conflicts that could be causing the timeout issue.
- When accessing Keycloak with a public IP, we either need to install a valid SSL certificate or disable SSL in the realm master settings.

**Comment by danielwebart** [comment]
Hi,
Answering the questions:

- Is the container port the same as the external port, i.e., are both set to 3000?
-> YES;

Check your firewall rules again to ensure that there are no restrictions or conflicts that could be causing the timeout issue.
-> We checked and theoretically everything is ok;

When accessing Keycloak with a public IP, we either need to install a valid SSL certificate or disable SSL in the realm master settings.
-> We checked that SSL is already disabled in the realm.

One observation is that when checking the call through the browser console, we see that after informing port 3000, the routine tries to redirect to the network's internal port. But this redirection happening from within the browser outside the internal network, maybe this is the problem?
![forms](https://github.com/AOT-Technologies/forms-flow-ai/assets/160621405/0b64d86d-2b77-4c7e-869a-22269bc1cdba)

**Comment by kiran-aot** [comment]
The browser try to call the URLs and ports that we have given in the .env file while we are installing the formsflow.ai. If we have given http://ip_address:8080 in the env file as keycloak URL it will try to access from public from the browser instead of calling internally

**Comment by kiran-aot** [comment]
Hi since no reply closing this issue , thank you
