### ISSUE TITLE
Camunda token expired when requests Form.io

### ISSUE THREAD

**Issue by andrepestana-aot** [AOT-Technologies/forms-flow-ai#215]
## Bug Report

I'm reporting it because I think it may be useful for someone testing it in their local machines. It shouldn't happen in a production environment though.

Camunda has a scheduled process "Formio Access Token Cache (Internal)" that tries to access the network but with WSL2 sometimes
the network is not available for some reason and the process fail.

### Setup

- Formsflow.ai version: 4.0.4
- Windows with WSL2
- Using configuration from forms-flow-ai/deployment/docker

### Steps to Reproduce

1. Configure and deploy formsflow.ai and start using it with a form and workflow
2. Put the windows machine to sleep overnight
3. Next day, try to submit a form and the message should be successful
4. Checking next tasks or the Camunda workflow you may notice the workflow process didn't start for the form you have just submitted
5. Checking Camunda server logs you may see something similar to this:
```
Warning: Nashorn engine is planned to be removed from a future JDK release

2022-02-01 16:57:16.767 ERROR 1 --- [nio-8080-exec-8] org.camunda.bpm.engine.context           : ENGINE-16004 Exception while closing command context: Unknown status code [440]


org.springframework.web.reactive.function.client.UnknownHttpStatusCodeException: Unknown status code [440]

at org.springframework.web.reactive.function.client.DefaultClientResponse.lambda$createException$1(DefaultClientResponse.java:224) ~[spring-webflux-5.3.8.jar!/:5.3.8]

Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 

Error has been observed at the following site(s):

|_ checkpoint ⇢ 440 from PATCH http://host.docker.internal:3001/form/61f1c27c52e45d624abe9758/submission/61f9666c42bd44fb993a13e9 [DefaultWebClient]

Stack trace:

at org.springframework.web.reactive.function.client.DefaultClientResponse.lambda$createException$1(DefaultClientResponse.java:224) ~[spring-webflux-5.3.8.jar!/:5.3.8]

at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.4.7.jar!/:3.4.7]

at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.7.jar!/:3.4.7]

at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:100) ~[reactor-core-3.4.7.jar!/:3.4.7]
```
6. Go to Camunda Cockpit Dashboard and check the processes: http://localhost:8000/camunda/app/cockpit/default/#/processes
7. Look for "Formio Access Token Cache (Internal)" and check its state. It may be in an error state.

### Steps to manually fix it 

1. Go to Camunda Tasklist (http://localhost:8000/camunda/app/tasklist/default/) and click on "Start process"
2. Click on "Formio Access Token Cache (Internal)" and "Start"
3. Go to Camunda Cockpit Dashboard and check the processes: http://localhost:8000/camunda/app/cockpit/default/#/processes
4. Look for "Formio Access Token Cache (Internal)" and check the latest execution state. It should be successful.
5. If you try a new form submission it should work now.

**Comment by abhishekbeesony** [comment]
@abhilash-aot Is there a way how this can be done without generating the token manually?..

**Comment by abhilash-aot** [comment]
@abhishekbeesony  We are working on a new mechanism to generate formio token differently without the workflow in camunda. That should fix this.

**Comment by abhilash-aot** [comment]
The new versions of forms-flow-ai from v4.0.5 already have a fix for this. Updated the Formio token mechanism. Hence closing the ticket
