### ISSUE TITLE
X-XSRF-TOKEN loss when visits Camunda 

### ISSUE THREAD

**Issue by coolhlm** [AOT-Technologies/forms-flow-ai#221]
The entire project has been deployed in my local machine,everything runs successfully when visits camunda whith 'http://localhost:8000/camunda', but something wrong when i change 'localhost' to  local ip ('http://192.168.19.12:8000/camunda').I got a 403 code  and lead to the login page when visited 'http://192.168.19.12:8000/camunda/api/engine/engine/default/group?maxResults=25&firstResult=0',it seens missing the request header :'X-XSRF-TOKEN'.
![image](https://user-images.githubusercontent.com/30930127/153401562-e373ecd3-5805-4f12-a9cf-f016d6d01b49.png)

Here is information of my request:
curl 'http://192.168.19.12:8000/camunda/api/engine/engine/default/group?maxResults=25&firstResult=0' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/hal+json, application/json; q=0.5' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://192.168.19.12:8000' \
  -H 'Referer: http://192.168.19.12:8000/camunda/app/welcome/default/' \
  -H 'Cookie: JSESSIONID=1FB251B3C8EA03FEC0676F87C9FBD660' \
  --data-raw '{"firstResult":0,"maxResults":25,"member":"formsflow-approver"}' \
  --compressed \
  --insecure

How can i fix this problem?

**Comment by sumesh-aot** [comment]
@coolhlm Thanks for contacting us. All of the components (forms, camunda) in this solution is protected by keycloak. The one attached in your screenshot is camunda login form (not keycloak login form). Can you check if the components are configured correct for keycloak authentication? May be try in an incognito window and watch the network tab and let us know ?
