### ISSUE TITLE
Not able to see submitted applications in tasks to approve

### ISSUE THREAD

**Issue by SumitMtx** [AOT-Technologies/forms-flow-ai#230]
I am trying a submit a form with two step approval process from client and review it from clerk/reviewer. Form submitted and also showing in applications while log in from clerk/reviewer but tasks are not displaying so how to review these applications.
Another scenario - For one application, task is showing and option to claim it but action section is not displaying to review it.
Please help.

**Comment by SumitMtx** [comment]
@abhilash-aot or anyone

**Comment by abhilash-aot** [comment]
Hi @SumitMtx  Sorry for the late Reply. 
Can you check the forms were published and associated to the workflow. Workflow associated forms only will have tasks.

@SumitMtx  Please Refer this Answer for Review Section not showing https://github.com/AOT-Technologies/forms-flow-ai/issues/237#issuecomment-1072023158

**Comment by xalcolm1** [comment]
Hello  @abhilash-aot , I have a workflow associated form (two-step approval) and tried adding the review section as is mentioned in #237, however neither of these changes allowed me to see the task in the tasks section

**Comment by sreehari-aot** [comment]
closing since we need more info to address the issue, feel free to reopen with more logs / info
