### ISSUE TITLE
WebAPI and BPM containers don't start properly

### ISSUE THREAD

**Issue by gagovictor** [AOT-Technologies/forms-flow-ai#231]
Hi, I followed the docker installation instructions and so far have not been able to get the forms-flow-webapi and forms-flow-bpm containers to run. All others are running as expected:

![docker1](https://user-images.githubusercontent.com/36168165/156389848-2f37fe68-9581-4110-81b3-21b2cbb292ae.JPG)

Upon examination, these are the error messages displayed:

forms-flow-webapi container:

![docker2](https://user-images.githubusercontent.com/36168165/156391589-63c5b830-8f0a-491a-b188-402625537428.JPG)
[forms-flow-webapi.txt](https://github.com/AOT-Technologies/forms-flow-ai/files/8170640/forms-flow-webapi.txt)

forms-flow-bpm container:

![docker3](https://user-images.githubusercontent.com/36168165/156391647-849673d8-ece5-4d31-8bea-e1fc5154d65c.JPG)
[forms-flow-bpm.txt](https://github.com/AOT-Technologies/forms-flow-ai/files/8170644/forms-flow-bpm.txt)

Both containers restart endlessly, always displaying the same output above. I have followed the instructions provided here https://github.com/AOT-Technologies/forms-flow-ai/tree/master/deployment/docker step by step even on different physical machines, always the same.

I have edited the .env files located in ./forms-flow-idm/keycloak/.env, ./forms-flow-analytics/.env and ./deployment/docker/.env. I believe I might be missing something but I can't figure out what it is by just looking at the output. Any help is appreciated.

**Comment by SawantDarshan** [comment]
@gagovictor  Did you able to solve this issue?

**Comment by sumesh-aot** [comment]
@gagovictor From logs and screenshot it looks like the container cannot reach localhost. Since you are using docker containers, localhost won't be reachable from within container. Can you try with IP address instead of localhost ?

**Comment by SawantDarshan** [comment]
@sumesh-aot I have already changed and tried with ip address still same issue is reflecting

**Comment by xalcolm1** [comment]
Any updates on this issue? I tried changing the ip address as well.

**Comment by sumesh-aot** [comment]
@xalcolm1 Team is working on a quick installation script to rule out any ip configuration issue, will let you know once it's in place.

**Comment by xalcolm1** [comment]
Update: I got my instance working, the ip address needed to be the docker ip address range.
I used the command `ip addr ` 
and then looked for docker, mine was called docker0, and used an address from that range.

**Comment by sumesh-aot** [comment]
Glad it's working for you. Thanks for the update!
