### ISSUE TITLE
Add AI-based Issue Ticket Enhancement

### ISSUE THREAD

**Issue by Vaibhavsg17** [AOT-Technologies/forms-flow-ai#2408]
Description
This PR introduces a framework to enhance the issue ticketing process with AI-driven features. The proposed changes aim to automate ticket categorization, labeling, and prioritization, improving the workflow and efficiency of issue management.

Features Added
AI-Based Categorization:
A machine learning model is integrated to categorize issues into predefined groups (e.g., Bug, Feature Request, Improvement).

Automatic Labeling:
Labels such as "High Priority" or "Urgent" are suggested based on the issue description using the AI model.

Priority Assignment:
Issues are assigned priority scores based on content analysis, aiding triage and decision-making.

GitHub Action Integration:
A GitHub Action is added to trigger the AI model and automatically apply predictions to newly created issues.

**Comment by Vaibhavsg17** [comment]
@sumesh-aot , @alanraju-aot 
I hope you're doing well!

I've created a pull request that introduces automated ticket categorization, labeling, and prioritization features to the project. This aligns with the repository's goals of enhancing workflows.

Please review the PR and provide feedback.

**Comment by sumesh-aot** [comment]
@Vaibhavsg17 I couldn't see any related PRs, can you please create a PR ?
