### ISSUE TITLE
formfs-flow-analytics -> keycloak error "LOGIN_ERROR" client_not_found

### ISSUE THREAD

**Issue by Constey** [AOT-Technologies/forms-flow-ai#242]
Hi there,

ive configured keycloak and analytics as described in: https://github.com/AOT-Technologies/forms-flow-ai/tree/master/forms-flow-analytics#configuration-of-keycloak-saml-setup 

But when trying to logon with saml Im getting a "invalid request" error:
![image](https://user-images.githubusercontent.com/11457386/160111519-df36ff7e-44df-4ff4-9f51-8b9a66b33ff6.png)

![image](https://user-images.githubusercontent.com/11457386/160111406-dcdb892e-c968-4b50-98f1-a98afd494e91.png)

The config .env of analytics is almost default:
![image](https://user-images.githubusercontent.com/11457386/160111618-19bc6a6c-2f25-455a-996b-1d012c3f8179.png)

Login to keycloak itself is working and the realm and client got created automatically.
![image](https://user-images.githubusercontent.com/11457386/160111696-87a70b59-4cf8-4c58-bfdf-eb9588e16b84.png)

Any ideas where I could have a look to?

Kind regards,
Constey

**Comment by HedBes** [comment]
Same issue here.

Did you resolve it?
