### ISSUE TITLE
Local Keycloak setup Error

### ISSUE THREAD

**Issue by HarumiSystem** [AOT-Technologies/forms-flow-ai#393]
1. I installed Docker and my Docker works fine.
2. Follow the steps to install [Local Keycloak setup](https://github.com/AOT-Technologies/forms-flow-ai/tree/master/forms-flow-idm/keycloak#local-keycloak-setup)
3. I use Run `docker-compose up -d`
4. Here is the problem I encountered, `Error response from daemon: Post "http://ipc/filesharing/prompt": context deadline exceeded (Client.Timeout exceeded while awaiting headers).`

please help me

![Capture](https://user-images.githubusercontent.com/105417327/168019326-a502a736-c3c4-4a8b-b82c-5e36222305e6.PNG)

**Comment by HarumiSystem** [comment]
[forms-flow-ai](https://github.com/AOT-Technologies/forms-flow-ai)/deployment/

Error response from daemon: Post "http://ipc/filesharing/prompt": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

![Capture](https://user-images.githubusercontent.com/105417327/168041439-d6fe2df4-0dfb-4610-b1f7-37cdd796e956.PNG)

**Comment by sumesh-aot** [comment]
@HarumiSystem Apologies for the delay. Can you please try easy installation setup [here](https://github.com/AOT-Technologies/forms-flow-ai/tree/develop/deployment/docker/bundle) and see if it works ?
