### ISSUE TITLE
Provide way to upload self signed certs for use

### ISSUE THREAD

**Issue by F5Brewery** [AOT-Technologies/forms-flow-ai#43]
Being this is a development/trial environment and some items in the requirements require SSL it would be good to be able to load self signed certs onto the various machines and have them trust them.  This is for both the environment and java.

In my very low level dev abilities I made this happen and posted this as a fix to an issue on the BPM.

It would be even more awesome if it could also be hosted as SSL with certs as well.

**Comment by abhilash-aot** [comment]
@F5Brewery Thanks for the suggestion. We jave taken this up. And also working on a local keycloack setup without ssl/providing a easier  import  setup of the same. Thanks and wait for the new release version 4. Thanks
