### ISSUE TITLE
Next button does not work on initial form save

### ISSUE THREAD

**Issue by F5Brewery** [AOT-Technologies/forms-flow-ai#46]
### Please provide information about your setup

- formsflow.ai Version: Docker Full Install
- Browser: Edge/Chrome
- Browser version: Latest

### Steps to Reproduce

1. Perform Full install of Docker
2. Open Formio and Create form
3. Save and Preview
4. Press Next...

### Observed Behaviour
You don't go to the next screen, click edit form and it will take you back, Press save , now next works.
If possible provide a screenshot to demonstrate the bug.

### Expected Behaviour
Next should take you to the screen to Associate workflow

**Comment by abhilash-aot** [comment]
Creating a ticket on this will solve on version 4

**Comment by abhilash-aot** [comment]
Solved on New v4 release
