### ISSUE TITLE
I can not install completely  

### ISSUE THREAD

**Issue by mojtaba1969** [AOT-Technologies/forms-flow-ai#489]
Dear all
I have tried two times to install your product without any errors but both time same thing happened.
localhost 8080 and 7000 and 3001 look like working.
localhost 3001(form.io) working but I am not sure working properly.
localhost 3000(formsflow) not loading properly and just some couple of circles are waving or dancing. 
localhost 8000 and 5000 are not reachable at all.
I have checked everything couple of times again and again and i believe something are wrong in installation instructions or some things are missed.
My machine is HP DL380 G9 with Ubuntu Linux OS
Please help and guide me if it is possible for you and you don't mind.
Thank you all guys in advance.
Your prompt reply is highly appreciated.
BR
Mojtaba

**Comment by xalcolm1** [comment]
I believe you are having the same problem I had, check out issue #231

**Comment by sumesh-aot** [comment]
@mojtaba1969 Can you please try easy bundle installation as [here](https://github.com/AOT-Technologies/forms-flow-ai/tree/develop/deployment/docker/bundle) and see if it works ?
