### ISSUE TITLE
Unable to perform IDM health check as documented

### ISSUE THREAD

**Issue by PhatWheZ** [AOT-Technologies/forms-flow-ai#558]
Hi there,

Followed the documentation to setup the Docker environment on Linux, I cannot complete Keycloaks health check
Health Check
The application should be up and available for use in http://localhost:8080/

Login Credentials
-----------------
User Name : admin
Password  : changeme

When I browse to: http://{redacted}:8080 and click on "Administration Console", I get "We are Sorry... HTTPS required"
I added the port mapping for 8443 and can sign in that way, but moving to setting up the analytics and the SAML setup. I cannot get passed that message

Any guidance/help would be appreciated

**Comment by PhatWheZ** [comment]
To Add... I completed the installation guide, however i cannot log in as a designer, user, reviewer, nor can I access Camunda by going to the IP address:8000/camunda as i get the same error message above "HTTPS required"

**Comment by nagannv** [comment]
@PhatWheZ
hope you have followed the below steps to overcome _We are Sorry... HTTPS required_

```
docker exec -it {contaierID} bash
cd keycloak/bin
./kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin
./kcadm.sh update realms/master -s sslRequired=NONE
```

**Comment by PhatWheZ** [comment]
@nagannv, thanks this did help me get into Keycloak using http://{IP-Address}:8080

However I have the same issue when going to http://{IP-Address}:7000 > SAML Login
http://{IP-Address}:8080/auth/realms/forms-flow-ai/protocol/saml?
The above link also giving out "We are Sorry... HTTPS required"

I did use the above as instructed.

Any further suggestions

**Comment by PhatWheZ** [comment]
@nagannv, I went through the entire build process from scratch again, ad at the end have the following issues:

https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-analytics/README.md
**HTTPS required** - Logout and login again using valid formsflow.ai keycloak user credentials. Default user credentials are provided [here](https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-idm/keycloak/README.md#formsflow-ai-user-credentials).

https://github.com/AOT-Technologies/forms-flow-ai/tree/master/deployment/docker
On the final Health Checks:
**HTTPS required with SAML** - Analytics should be up and available for use at port defaulted to 7000 i.e. http://localhost:7000/
**HTTPS required** - Business Process Engine should be up and available for use at port defaulted to 8000 i.e. http://localhost:8000/camunda/
Working - FormIO should be up and available for use at port defaulted to 3001 i.e. http://localhost:3001/
Working - formsflow.ai Rest API should be up and available for use at port defaulted to 5000 i.e. http://localhost:5000/checkpoint
**3 Bouncing dots** - formsflow.ai web application should be up and available for use at port defaulted to 3000 i.e. http://localhost:3000/

**Comment by PhatWheZ** [comment]
Came right after disabling SSL for realm/forms-flow-ai from the GUI
