### ISSUE TITLE
API token authentication issue.

### ISSUE THREAD

**Issue by Arekku21** [AOT-Technologies/forms-flow-ai#559]
Hi everyone ! I am currently running into an authentication issue regarding the forms flow ai api. 

The setup I have used is the single installation local docker setup. I have done the correct method to get the token thru the postman post rest api to get the token and tried to authenticate access to the api. 

Unfortunately, I am running into errors. I have tried several checks to ensure that the token is valid. Firstly, I have token debugger to check if the token is valid. Additionally, I also have tried other methods such as entering the Keycloak api to see if the token was valid.

![image](https://user-images.githubusercontent.com/70086993/176852033-9f6246d4-e31b-41e0-ac93-04033773b9d5.png)
As mentioned in documentation, I have followed the way they did the post request for the bearer token. 

![image](https://user-images.githubusercontent.com/70086993/176852743-ad447014-5f5f-4173-973d-4a6e1e635393.png)
This is the get request to try and get the api for the application for an example using the bearer token.

Unfortunately, with all this procedures it returns me an invalid token error. It mentions that the authentication or time limit of the token is invalid. 

Any help would be appreciated ! Thank you so much !

**Comment by sumesh-aot** [comment]
@Arekku21 It could be issue with wrong `iss`. Can you try generating the token using the IP address URL instead of localhost ?

**Comment by Arekku21** [comment]
Thank you so much for the reply ! Ill give it a try
