### ISSUE TITLE
Problems during docker build

### ISSUE THREAD

**Issue by waterboo** [AOT-Technologies/forms-flow-ai#56]
While doing

docker-compose -f docker-compose-linux.yml build

I get: ERROR: Service 'forms-flow-bpm' failed to build.

Possibly due to two missing files:

https://app.camunda.com/nexus/repository/camunda-bpm-community-extensions-snapshots/org/camunda/bpm/camunda-bom/7.13.0/camunda-bom-7.13.0.pom

https://app.camunda.com/nexus/repository/camunda-bpm-community-extensions-snapshots/org/springframework/boot/spring-boot-dependencies/2.2.7.RELEASE/spring-boot-dependencies-2.2.7.RELEASE.pom

Thank you.

**Comment by sumathi-thirumani-aot** [comment]
@waterboo Can you please let me know which branch used.

**Comment by waterboo** [comment]
git clone https://github.com/AOT-Technologies/forms-flow-ai

Master branch.

Thanks.

**Comment by abhilash-aot** [comment]
This is fixed in version 4 .
