### ISSUE TITLE
Failed building docker image

### ISSUE THREAD

**Issue by hgrecco** [AOT-Technologies/forms-flow-ai#714]
### Please provide information about your setup

- formsflow.ai Version: Downloaded from github 2bcf8462c7edb486cbe4c9eead666cb1e92a8596
- Docker version 20.10.12, build e91ed57
- macOS 12.4

### Steps to Reproduce

1. Build the docker image following the instructions
   `docker-compose -f docker-compose-linux.yml up --build -d`

### Observed Behaviour
```
 > [build-stage 10/10] RUN npm run build:
#17 2.600
#17 2.600 > formsflow-ai-react@4.0.6 build /forms-flow-web/app
#17 2.600 > react-scripts --max_old_space_size=6144 build
#17 2.600
#17 6.769 Creating an optimized production build...
#17 209.4 The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
#17 210.0 npm ERR! code ELIFECYCLE
#17 210.0 npm ERR! errno 1
#17 210.0 npm ERR! formsflow-ai-react@4.0.6 build: `react-scripts --max_old_space_size=6144 build`
#17 210.0 npm ERR! Exit status 1
#17 210.0 npm ERR!
#17 210.0 npm ERR! Failed at the formsflow-ai-react@4.0.6 build script.
#17 210.0 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#17 210.1
#17 210.1 npm ERR! A complete log of this run can be found in:
#17 210.1 npm ERR!     /root/.npm/_logs/2022-08-03T21_41_21_367Z-debug.log
```

**Comment by alanraju-aot** [comment]
@hgrecco The error occurred due to the excess memory. Just prune everything in the docker. Follow the command below:
1. docker system prune
2. docker container prune
3. docker network prune
4. docker image prune
If the image has not deleted, you might need to clear all the images manually by entering into the docker desktop.
