### ISSUE TITLE
Server crashes when I build the docker images

### ISSUE THREAD

**Issue by sarvmai** [AOT-Technologies/forms-flow-ai#731]
Hello All,

I am in need of some help here, been following the following installation guide
https://github.com/AOT-Technologies/forms-flow-ai/tree/master/deployment/docker

The keycloak, Redash, and forms.io page which listen on 8080, 3001 and 7000 ports come up fine but the other 3 dont. Everytime the build is taking around 2 hours and at the end of it the server itself crashes and logs me out. 

![image](https://user-images.githubusercontent.com/104489117/183583203-8f2e6699-e5d3-4eda-9d57-e8262dbc03a9.png)

![image](https://user-images.githubusercontent.com/104489117/183583238-cab4c4dd-8b4d-4c31-b55a-3f65aa10b7eb.png)

![image](https://user-images.githubusercontent.com/104489117/183583475-90c14aef-4cd1-461d-a7a8-4d44a6f3bf6b.png)

Any help??

**Comment by alanraju-aot** [comment]
Can you just expose what the error actually is? Just show the error message that you get and also if it breaks just send the loggs of the following containers.
