### ISSUE TITLE
When running the forms flow web

### ISSUE THREAD

**Issue by abhishekbeesony** [AOT-Technologies/forms-flow-ai#78]
Hello , 

When im running the forms flow webcomponent, i  getting this kind of error 

It keeps on rotating.
![image](https://user-images.githubusercontent.com/66721640/117105535-4be29080-ad8f-11eb-9f35-7875fb5bb020.png)

Please help.

**Comment by abhilash-aot** [comment]
Please check for the keycloak configuration done. Check this link for more info on setting up with keycloak  https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-idm/keycloak-setup.md

**Comment by abhishekbeesony** [comment]
> Please check for the keycloak configuration done. Check this link for more info on setting up with keycloak https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-idm/keycloak-setup.md

Thank you abhilash.

**Comment by abhilash-aot** [comment]
Keycloack configuration would be made easier with a import step in coming release so closing it now.
