### ISSUE TITLE
When running the forms flow api web and the forms flow api web db, getting error on docker.

### ISSUE THREAD

**Issue by abhishekbeesony** [AOT-Technologies/forms-flow-ai#79]
![image](https://user-images.githubusercontent.com/66721640/117241302-e2708980-ae43-11eb-8bd3-c1ae0702cfe8.png)

![image](https://user-images.githubusercontent.com/66721640/117241327-f61bf000-ae43-11eb-8874-29d7b6b2af44.png)

Please advice and thank you very much.

**Comment by kurianbenoy-aot** [comment]
@abhishekbeesony have you added all the variables in environment files(.env)? . If not please refer:

https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-api/sample.env

Also ensure the keycloak setup is being done for the project

**Comment by abhishekbeesony** [comment]
> @abhishekbeesony have you added all the variables in environment files(.env)? . If not please refer:
> 
> https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-api/sample.env
> 
> Also ensure the keycloak setup is being done for the project

**Comment by abhishekbeesony** [comment]
> > @abhishekbeesony have you added all the variables in environment files(.env)? . If not please refer:
> > https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-api/sample.env
> > Also ensure the keycloak setup is being done for the project


**Here is my env file. One thing I'm not understanding should i install the prostgresql and mongodb on my pc locally and if not what should be the username and password?** Thank you

##Environment variables for adaptive tier (Python Webapi) Datastore
WEB_API_DATABASE_URL=postgresql://postgres:changeme@forms-flow-webapi-db:5432/formsflow
WEB_API_POSTGRES_USER=postgres
WEB_API_POSTGRES_PASSWORD=changeme
WEB_API_POSTGRES_DB=formsflow


KEYCLOAK_TOKEN_URL=http://localhost:8080/auth/realms/forms-flow-ai/protocol/openid-connect/token
KEYCLOAK_JWT_OIDC_CONFIG=http://localhost:8080/auth/realms/forms-flow-ai/.well-known/openid-configuration
KEYCLOAK_JWT_OIDC_JWKS_URI=http://localhost:8080/auth/realms/forms-flow-ai/protocol/openid-connect/certs
KEYCLOAK_JWT_OIDC_ISSUER=http://localhost:8080/auth/realms/forms-flow-ai
KEYCLOAK_BPM_CLIENTID=forms-flow-bpm
KEYCLOAK_BPM_CLIENTSECRET=f681ead7-0698-466f-893c-ca68127d5a76
KEYCLOAK_WEB_CLIENTID=forms-flow-web


CAMUNDA_API_URI=http://localhost:8000/camunda
WEB_API_BASE_URL=http://localhost:5000

MONGODB_URI=mongodb://'':''@forms-flow-forms-db:27017/admin?authMechanism=SCRAM-SHA-1&authSource=admin

**Comment by kurianbenoy-aot** [comment]
Hi @abhishekbeesony, the docker setup on installation will create a postgres installation also, so you don't need to change any env variables. For MongoDB the username is the database username you want to login and password is the database password. I personally haven't tested if MONGODB works locally, yet it should work technically if you are running the whole formsflow.ai solution in `deployment/docker` using same mongodb database as formIO.

**Comment by abhishekbeesony** [comment]
> deployment/docker

Thank you kurianbenoy-aot. i have running the components one by one and still getting this error  on forms-flow-api


********************************************************************************

WARNING: POSTGRES_HOST_AUTH_METHOD has been set to "trust". This will allow

anyone with access to the Postgres port to access your database without

a password, even if POSTGRES_PASSWORD is set. See PostgreSQL

documentation about "trust":

https://www.postgresql.org/docs/current/auth-trust.html

In Docker's default configuration, this is effectively any other

container on the same system.


It is not recommended to use POSTGRES_HOST_AUTH_METHOD=trust. Replace

it with "-e POSTGRES_PASSWORD=password" instead to set a password in

"docker run".

The files belonging to this database system will be owned by user "postgres".

This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".

The default database encoding has accordingly been set to "UTF8".

The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok

creating subdirectories ... ok

selecting default max_connections ... 100

selecting default shared_buffers ... 128MB

selecting default timezone ... Etc/UTC

selecting dynamic shared memory implementation ... posix

creating configuration files ... ok

running bootstrap script ... ok

performing post-bootstrap initialization ... ok

syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections

You can change this by editing pg_hba.conf or using the option -A, or

--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2021-05-06 09:31:11.904 UTC [48] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"

2021-05-06 09:31:11.969 UTC [49] LOG: database system was shut down at 2021-05-06 09:31:11 UTC

2021-05-06 09:31:11.987 UTC [48] LOG: database system is ready to accept connections

done

server started

CREATE DATABASE

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2021-05-06 09:31:12.997 UTC [48] LOG: received fast shutdown request

waiting for server to shut down....2021-05-06 09:31:13.018 UTC [48] LOG: aborting any active transactions

2021-05-06 09:31:13.026 UTC [48] LOG: background worker "logical replication launcher" (PID 55) exited with exit code 1

2021-05-06 09:31:13.026 UTC [50] LOG: shutting down

2021-05-06 09:31:13.125 UTC [48] LOG: database system is shut down

server stopped

PostgreSQL init process complete; ready for start up.

2021-05-06 09:31:13.221 UTC [1] LOG: listening on IPv4 address "0.0.0.0", port 5432

2021-05-06 09:31:13.221 UTC [1] LOG: listening on IPv6 address "::", port 5432

2021-05-06 09:31:13.248 UTC [1] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"

2021-05-06 09:31:13.304 UTC [76] LOG: database system was shut down at 2021-05-06 09:31:13 UTC

2021-05-06 09:31:13.322 UTC [1] LOG: database system is ready to accept connections

2021-05-06 09:31:14.290 UTC [83] LOG: invalid length of startup packet

2021-05-06 09:31:14.290 UTC [84] LOG: invalid length of startup packet

2021-05-06 09:31:16.324 UTC [85] LOG: invalid length of startup packet

2021-05-06 09:31:16.396 UTC [86] LOG: invalid length of startup packet

2021-05-06 09:31:17.550 UTC [87] LOG: invalid length of startup packet

2021-05-06 09:31:17.572 UTC [89] LOG: invalid length of startup packet

2021-05-06 09:31:17.575 UTC [88] LOG: invalid length of startup packet

2021-05-06 09:31:18.574 UTC [90] LOG: invalid length of startup packet

2021-05-06 09:31:18.594 UTC [91] LOG: invalid length of startup packet

2021-05-06 09:31:18.604 UTC [92] LOG: invalid length of startup packet

2021-05-06 09:31:19.591 UTC [93] LOG: invalid length of startup packet

2021-05-06 09:31:19.623 UTC [94] LOG: invalid length of startup packet

2021-05-06 09:31:19.626 UTC [95] LOG: invalid length of startup packet








Sign in

forms-flow-api_forms-flow-webapi_1forms-flow-api_forms-flow-webapi
RUNNING



**This is for the forms flow api**

WARNING: SECRET_KEY being set as a one-shot

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

[nltk_data] Downloading package punkt to /root/nltk_data...

[nltk_data] Unzipping tokenizers/punkt.zip.

[nltk_data] Downloading package subjectivity to /root/nltk_data...

[nltk_data] Unzipping corpora/subjectivity.zip.

Configure logging, from conf:/usr/local/lib/python3.8/site-packages/api/logging.conf

Traceback (most recent call last):

File "/usr/local/lib/python3.8/urllib/request.py", line 1354, in do_open

h.request(req.get_method(), req.selector, req.data, headers,

File "/usr/local/lib/python3.8/http/client.py", line 1252, in request

self._send_request(method, url, body, headers, encode_chunked)

File "/usr/local/lib/python3.8/http/client.py", line 1298, in _send_request

self.endheaders(body, encode_chunked=encode_chunked)

File "/usr/local/lib/python3.8/http/client.py", line 1247, in endheaders

self._send_output(message_body, encode_chunked=encode_chunked)

File "/usr/local/lib/python3.8/http/client.py", line 1007, in _send_output

self.send(msg)

File "/usr/local/lib/python3.8/http/client.py", line 947, in send

self.connect()

File "/usr/local/lib/python3.8/http/client.py", line 918, in connect

self.sock = self._create_connection(

File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection

raise err

File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection

sock.connect(sa)

OSError: [Errno 99] Cannot assign requested address


During handling of the above exception, another exception occurred:

File "manage.py", line 14, in <module>

APP = create_app()

File "/usr/local/lib/python3.8/site-packages/api/__init__.py", line 30, in create_app

setup_jwt_manager(app, jwt)

File "/usr/local/lib/python3.8/site-packages/api/__init__.py", line 49, in setup_jwt_manager

jwt_manager.init_app(app)

File "/usr/local/lib/python3.8/site-packages/flask_jwt_oidc/jwt_manager.py", line 80, in init_app

jurl = urlopen(url=self.well_known_config)

File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen

return opener.open(url, data, timeout)

File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open

response = self._open(req, data)

File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open

result = self._call_chain(self.handle_open, protocol, protocol +

File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain

result = func(*args)

File "/usr/local/lib/python3.8/urllib/request.py", line 1383, in http_open

return self.do_open(http.client.HTTPConnection, req)

File "/usr/local/lib/python3.8/urllib/request.py", line 1357, in do_open

raise URLError(err)

urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

[nltk_data] Package vader_lexicon is already up-to-date!

[nltk_data] Package punkt is already up-to-date!

[nltk_data] Package subjectivity is already up-to-date!


Please help

**Comment by kurianbenoy-aot** [comment]
Can you share the .env variables you used? Have you completed the setup of keycloak configuration as @abhilash-aot pointed out?

**Comment by abhishekbeesony** [comment]
> Can you share the .env variables you have used?
> 
> Have you completed the setup of keycloak configuration as @abhilash-aot pointed out?

Here is the env  and keycloak configuration has been done same as @abhilash-aot  pointed out. 

##Environment variables for adaptive tier (Python Webapi) Datastore
WEB_API_DATABASE_URL=postgresql://postgres:changeme@forms-flow-webapi-db:5432/formsflow
WEB_API_POSTGRES_USER=postgres
WEB_API_POSTGRES_PASSWORD=changeme
WEB_API_POSTGRES_DB=formsflow

KEYCLOAK_TOKEN_URL=http://localhost:8080/auth/realms/forms-flow-ai/protocol/openid-connect/token
KEYCLOAK_JWT_OIDC_CONFIG=http://localhost:8080/auth/realms/forms-flow-ai/.well-known/openid-configuration
KEYCLOAK_JWT_OIDC_JWKS_URI=http://localhost:8080/auth/realms/forms-flow-ai/protocol/openid-connect/certs
KEYCLOAK_JWT_OIDC_ISSUER=http://localhost:8080/auth/realms/forms-flow-ai
KEYCLOAK_BPM_CLIENTID=forms-flow-bpm
KEYCLOAK_BPM_CLIENTSECRET=f681ead7-0698-466f-893c-ca68127d5a76
KEYCLOAK_WEB_CLIENTID=forms-flow-web

CAMUNDA_API_URI=http://localhost:8000/camunda
WEB_API_BASE_URL=http://localhost:5000

MONGODB_URI=mongodb://'':''@forms-flow-forms-db:27017/admin?authMechanism=SCRAM-SHA-1&authSource=admin

Thank you

**Comment by kurianbenoy-aot** [comment]
@abhishekbeesony you need to set CAMUNDA_API_URL with the IP of your system instead of setting the localhost variable value

![image](https://user-images.githubusercontent.com/70306694/117449079-2dca8b00-af5d-11eb-9c9a-563d04712f35.png)

**Comment by abhishekbeesony** [comment]
@kurianbenoy-aot  i have replace my ip as requested.  Im still getting the above issue and it kept restating every minute.

Can we talk or share a contact details with me?. 

Thank you.
![image](https://user-images.githubusercontent.com/66721640/117464604-e0045180-af61-11eb-89ef-05879b0cbfa9.png)
![image](https://user-images.githubusercontent.com/66721640/117464728-01653d80-af62-11eb-8591-7ffa08fd84c7.png)

**Comment by kurianbenoy-aot** [comment]
@abhishekbeesony you will need a SSL certificate for Keycloak credentials for running any component for formsflow.ai like  `forms-flow-api`, `forms-flow-bpm` etc. 

In your environment variables the KEYCLOAK looks like it's being run from localhost. That won't work for formsflow.ai solution.

If you liked the project do give us a star ⭐ in our repository. 

If you want to involve us in formsflow.ai integration for your organisation? Feel free to [contact us here](https://www.aot-technologies.com/contact-us/)

**Comment by abhishekbeesony** [comment]
> @abhishekbeesony you will need a SSL certified Keycloak credentials for running any component for formsflow.ai like `forms-flow-api`, `forms-flow-bpm` etc.
> 
> In your environment variables the KEYCLOAK looks like it's being run from localhost. That won't work for formsflow.ai solution. That is why the urlib3 error occurs.
> 
> If you liked the project do give us a star ⭐ in our repository.
> 
> If you want to involve us in formsflow.ai integration for your organisation? Feel free to [contact us here](https://www.aot-technologies.com/contact-us/)

@kurianbenoy-aot  is this error also relate to the https?

![image](https://user-images.githubusercontent.com/66721640/117515846-82472800-afa8-11eb-9d5e-d949a2c89afd.png)

**Comment by kurianbenoy-aot** [comment]
Yeah looks like the same issue to me because of not having SSL signed Keycloak credentials.

**Comment by abhilash-aot** [comment]
Will be Improving the readme/providing keycloak config for import for easier spin up in version 4
