### ISSUE TITLE
When running the forms flow bpm -Camunda, getting issue.

### ISSUE THREAD

**Issue by abhishekbeesony** [AOT-Technologies/forms-flow-ai#80]
Hello Sir, 
![image](https://user-images.githubusercontent.com/66721640/117250547-72b6ca80-ae54-11eb-93ea-d6378ae72789.png)

Please help.

**Comment by abhishekbeesony** [comment]
Hello, 

Getting this kind of error : 

![image](https://user-images.githubusercontent.com/66721640/117400717-45315600-af14-11eb-8cca-38e65f21c07a.png)


Please advice.

**Comment by kurianbenoy-aot** [comment]
Looks like the same error @abhishekbeesony . You will need  a SSL certified  Keycloak credentials to run formsflow.ai solution

**Comment by abhishekbeesony** [comment]
Thank you @kurianbenoy-aot. How can i get an SSL certified credentials?. Please help.

**Comment by abhilash-aot** [comment]
Will be updating the readme  documents for keycloack and associated config . Also will add a import json for easier realm export
