### ISSUE TITLE
Getting error when running the forms flow forms 

### ISSUE THREAD

**Issue by abhishekbeesony** [AOT-Technologies/forms-flow-ai#81]
Hello, 

Can you please help why are getting this kind of error ?

![image](https://user-images.githubusercontent.com/66721640/117289679-f0db9700-ae7d-11eb-8261-dfc14d0f3da6.png)

**Comment by abhilash-aot** [comment]
Have created a JIra ticket at our side to look into this issue. Will update once its fixed. Thanks.

**Comment by abhilash-aot** [comment]
The issue is fixed in new release. 
- For further update on this try` docker volume prune` to remove any dangling images.  and delete the mongod folder in the deployment folder and start the forms-flow-forms again with up --build option
