### ISSUE TITLE
Form Process Failed & Error in creating form Process mapper

### ISSUE THREAD

**Issue by 0plm9okn8ijb** [AOT-Technologies/forms-flow-ai#815]
## Bug Report
I am having issue with Form Process Failed & Error in creating form Process mapper. I have followed all the instruction given in the instruction but when creating form, above mentioned issues popped up and it seemed that the form doesn't save. Also it can not be viewed from the client side.  
### Please provide information about your setup
I have followed the docker full deployment method.  
- formsflow.ai Version: 5.0
- Browser: Chromebook
- Browser version: Version 104.0.5112.102

### Steps to Reproduce
The docker full deployment
### Observed Behavior
![Screenshot 2022-08-28 125327](https://user-images.githubusercontent.com/94233162/187058484-464bbdfb-e4ff-4cfd-a1aa-feec45b83c14.png)

**Comment by sumesh-aot** [comment]
@0plm9okn8ijb Can you please share the API logs?

**Comment by sreehari-aot** [comment]
Closing this issue since it is fixed in the latest release!
