### ISSUE TITLE
Configuration file problem

### ISSUE THREAD

**Issue by jiuaige** [AOT-Technologies/forms-flow-ai#84]
For the following parameters, I see the official website and ask me to request this address to obtain

[
    {
        "_id": "60814598157e62584d74c7b1",
        "description": "A role for Administrative Users.",
        "default": false,
        "admin": true,
        "title": "Administrator",
        "machineName": "administrator",
        "created": "2021-04-22T09:44:56.724Z",
        "modified": "2021-05-17T02:06:47.009Z"
    },
    {
        "_id": "60814598157e62ac7674c7b3",
        "description": "A role for Anonymous Users.",
        "default": true,
        "admin": false,
        "title": "Anonymous",
        "machineName": "anonymous",
        "created": "2021-04-22T09:44:56.809Z",
        "modified": "2021-05-17T02:06:47.029Z"
    },
    {
        "_id": "60814598157e6269ca74c7b2",
        "description": "A role for Authenticated Users.",
        "default": false,
        "admin": false,
        "title": "Authenticated",
        "machineName": "authenticated",
        "created": "2021-04-22T09:44:56.802Z",
        "modified": "2021-05-17T02:06:47.022Z"
    }
]

CLIENT_ROLE_ID=60814598157e62ac7674c7b3
DESIGNER_ROLE_ID=60814598157e62584d74c7b1
REVIEWER_ROLE_ID=60814598157e62ac7674c7b3
ANONYMOUS_ID=60814598157e62ac7674c7b3
USER_RESOURCE_ID=1

How do I get the values of CLIENT_ROLE_ID and USER_RESOURCE_ID？
Thank u,guards

**Comment by abhilash-aot** [comment]
Use the json import for forms as :  https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-forms/sample.json     And check this link https://github.com/AOT-Technologies/forms-flow-ai/tree/master/deployment/docker for  environment variables for forms-flow-ai  for how to get the data.

**Comment by jiuaige** [comment]
> Use the json import for forms as : https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-forms/sample.json And check this link https://github.com/AOT-Technologies/forms-flow-ai/tree/master/deployment/docker for environment variables for forms-flow-ai for how to get the data.



> Use the json import for forms as : https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-forms/sample.json And check this link https://github.com/AOT-Technologies/forms-flow-ai/tree/master/deployment/docker for environment variables for forms-flow-ai for how to get the data.

**Comment by jiuaige** [comment]
> Use the json import for forms as : https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-forms/sample.json And check this link https://github.com/AOT-Technologies/forms-flow-ai/tree/master/deployment/docker for environment variables for forms-flow-ai for how to get the data.

I will try the method you mentioned right away. I have encountered other problems here. Can I continue to communicate with you? Can you give me some contact information, email or some social network account?
