### ISSUE TITLE
No task problem

### ISSUE THREAD

**Issue by jiuaige** [AOT-Technologies/forms-flow-ai#86]
1  When I compile the form, click next, then select One Step Approval, click save, the error message of the docker_forms-flow-forms container is as follows

formio:log Token Using normal token +72ms
  formio:log User external +0ms
  formio:cache:loadForm string: 60814598157e62122774c7b4 +52ms
  formio:cache:loadForm Caching result +1ms
  formio:cache:loadSubForms Loading subforms for 60814598157e62122774c7b4 +60ms
  formio:util:getUrlParams Url {
  formio:util:getUrlParams   protocol: null,
  formio:util:getUrlParams   slashes: null,
  formio:util:getUrlParams   auth: null,
  formio:util:getUrlParams   host: null,
  formio:util:getUrlParams   port: null,
  formio:util:getUrlParams   hostname: null,
  formio:util:getUrlParams   hash: null,
  formio:util:getUrlParams   search: null,
  formio:util:getUrlParams   query: null,
  formio:util:getUrlParams   pathname: '/current',
  formio:util:getUrlParams   path: '/current',
  formio:util:getUrlParams   href: '/current'
  formio:util:getUrlParams } +9ms
  formio:util:getUrlParams { current: '' } +0ms
  formio:db Connection exists +9ms
  formio:sanityCheck Checking GET +9ms
  formio:sanityCheck No Response and Less than 10 seconds +0ms
  formio:util:idToBson Unknown _id given: external, typeof: string +8ms
  formio:cache:loadSubmission Searching for form: 60814598157e62122774c7b4, and submission: external +8ms
  formio:cache:loadSubmission {
  formio:cache:loadSubmission   _id: 'external',
  formio:cache:loadSubmission   form: 60814598157e62122774c7b4,
  formio:cache:loadSubmission   deleted: { '$eq': null }
  formio:cache:loadSubmission } +0ms
  formio:cache:loadSubmission CastError: Cast to ObjectId failed for value "external" at path "_id" for model "submission"
  formio:cache:loadSubmission     at model.Query.exec (/.npm-packages/node_modules/mongoose/lib/query.js:4358:21)
  formio:cache:loadSubmission     at Object.loadSubmission (/forms-flow-forms/app/src/cache/cache.js:250:81)
  formio:cache:loadSubmission     at /forms-flow-forms/app/src/middleware/tokenHandler.js:195:15
  formio:cache:loadSubmission     at Object.alter (/forms-flow-forms/app/src/util/hook.js:39:18)
  formio:cache:loadSubmission     at /forms-flow-forms/app/src/middleware/tokenHandler.js:145:12
  formio:cache:loadSubmission     at /.npm-packages/node_modules/jsonwebtoken/verify.js:223:12
  formio:cache:loadSubmission     at getSecret (/.npm-packages/node_modules/jsonwebtoken/verify.js:90:14)
  formio:cache:loadSubmission     at Object.module.exports [as verify] (/.npm-packages/node_modules/jsonwebtoken/verify.js:94:10)
  formio:cache:loadSubmission     at /forms-flow-forms/app/src/middleware/tokenHandler.js:124:9
  formio:cache:loadSubmission     at Layer.handle [as handle_request] (/.npm-packages/node_modules/express/lib/router/layer.js:95:5)
  formio:cache:loadSubmission     at trim_prefix (/.npm-packages/node_modules/express/lib/router/index.js:317:13)
  formio:cache:loadSubmission     at /.npm-packages/node_modules/express/lib/router/index.js:284:7
  formio:cache:loadSubmission     at Function.process_params (/.npm-packages/node_modules/express/lib/router/index.js:335:12)
  formio:cache:loadSubmission     at next (/.npm-packages/node_modules/express/lib/router/index.js:275:10)
  formio:cache:loadSubmission     at cors (/.npm-packages/node_modules/cors/lib/index.js:188:7)
  formio:cache:loadSubmission     at /.npm-packages/node_modules/cors/lib/index.js:224:17 +1ms
  formio:middleware:tokenHandler {
  formio:middleware:tokenHandler   _id: 'external',
  formio:middleware:tokenHandler   roles: [
  formio:middleware:tokenHandler     '60a221e4ed7a63ec0be5d173',
  formio:middleware:tokenHandler     '60a221e4ed7a6355cbe5d172',
  formio:middleware:tokenHandler     '60814598157e62584d74c7b1'
  formio:middleware:tokenHandler   ]
  formio:middleware:tokenHandler } +9ms
  formio:log Token Using normal token +9ms
  formio:log User external +0ms
  formio:cache:loadForm string: 60814598157e62122774c7b4 +8ms
  formio:cache:loadForm Caching result +1ms
  formio:cache:loadSubForms Loading subforms for 60814598157e62122774c7b4 +9ms

2 Log in to the service of port 3000, click task to return null

3 Log in to the service on port 8000, click Start process, and get the error message as follows
The process could not be started. :
404 Not Found: [<!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Cannot PUT /form/</pre> </body> </html> ]

Thank you very much for the open source framework you provide, I enjoy this framework, please help me see my questions, thanks

**Comment by jiuaige** [comment]
- Create form

![image](https://user-images.githubusercontent.com/20938790/117521746-fd790000-afe1-11eb-910a-0aaa9a6c6251.png)

- Edit some information

![image](https://user-images.githubusercontent.com/20938790/117521765-14b7ed80-afe2-11eb-8774-2c7acc8e0096.png)

- Applications
![image](https://user-images.githubusercontent.com/20938790/117521754-0669d180-afe2-11eb-9d3d-355fe42d3051.png)

- But no task display
![image](https://user-images.githubusercontent.com/20938790/117521831-78dab180-afe2-11eb-9015-a2eea1835c62.png)

- Question1:How can there be tasks and corresponding processes, do I need to open the process in the bmp service?

- Question2:Start process failed

![image](https://user-images.githubusercontent.com/20938790/117521885-bc352000-afe2-11eb-9a75-3af7c5ac603d.png)

**Comment by abhilash-aot** [comment]
Create a form submission with submitNew Button to trigger a task creation from Ui /forms page(the first screenshot you gave). If the form is associated to that workflow that particular workflow task will be created .

**Comment by jiuaige** [comment]
But when i submit New Button to trigger a task creation，no task has been created,and error occured
![image](https://user-images.githubusercontent.com/20938790/117528829-c8cb6f80-b006-11eb-9d31-f76f06c9c3f9.png)

Can you tell me how to correctly associate the form with the process？

**Comment by abhilash-aot** [comment]
@jiuaige  Please try with the new release . The issues would be fixed. Thanks for trying the solution
