### ISSUE TITLE
Either documentation is incorrect or there are issues with your docker-compose files 

### ISSUE THREAD

**Issue by parsonsalan1** [AOT-Technologies/forms-flow-ai#92]
Constant errors when spinning up docker-compose files. I try to follow the directions but most of what I'm doing is guessing, however some of it is pretty straight forward, but still get bugs, such as can't connect to the mongo db, however when I remove the password it works just fine. So bugs there too.

**Comment by parsonsalan1** [comment]
turns out keycloak needs to be https, any guides being made?

**Comment by abhilash-aot** [comment]
@parsonsalan1  Yes we are updating the documentation for the same . Will have a version 4 release by next week with more updates.
