### ISSUE TITLE
History Application always empty. Do i need to do some configuration? Application status always new not did changed after approved.

### ISSUE THREAD

**Issue by abhishekbeesony** [AOT-Technologies/forms-flow-ai#94]
![image](https://user-images.githubusercontent.com/66721640/119926628-c797bd80-bf88-11eb-916a-3da1aac47c88.png)
![image](https://user-images.githubusercontent.com/66721640/119926710-eb5b0380-bf88-11eb-987a-5f406af75fc6.png)
Thank you

**Comment by abhilash-aot** [comment]
This is fixed in the new release please check . Thanks
