### ISSUE TITLE
Error with Installation

### ISSUE THREAD

**Issue by sch-publicplan** [AOT-Technologies/forms-flow-ai#982]
### Please provide information about your setup

- formsflow.ai Version: 5.0.2
- Browser: Chrome
- Browser version:  106.0.5249.119

### Steps to Reproduce

Install formsflow on VM Linux Ubuntu
Info about VM:
---------------------------------------------------
Welcome to Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-52-generic x86_64)

  * Documentation:  https://help.ubuntu.com/
  * Management:     https://landscape.canonical.com/
  * Support:        https://ubuntu.com/advantage

   System information as of Thu Oct 27 10:04:03 AM CEST 2022

   System load:                      0.5205078125
   Usage of /:                       17.3% of 126.90GB
   Memory usage:                     30%
   Swap usage:                       0%
   Processes:                        283
   Users logged in:                  0
------------------------------------------------
In Attachment you will find more logs

Please check the error log in mongo Container. Attachment

### Observed Behaviour

If possible provide a screenshot to demonstrate the bug.

### Expected Behaviour

![1](https://user-images.githubusercontent.com/80529915/198228230-77ff4812-67ab-4116-96ab-716e04b25007.png)
![2](https://user-images.githubusercontent.com/80529915/198228235-04c81339-ee86-4e6e-be8a-3ecc5dab21e1.png)
![3](https://user-images.githubusercontent.com/80529915/198228237-59722243-1370-4bb6-86e4-c0760bbd6ca3.png)
[log_document_db.log](https://github.com/AOT-Technologies/forms-flow-ai/files/9877228/log_document_db.log)
![fehler](https://us
[error mongo container.txt](https://github.com/AOT-Technologies/forms-flow-ai/files/9877237/error.mongo.container.txt)
er-images.githubusercontent.com/80529915/198228270-fc72020d-9e42-41b2-aad0-a5fd4b6d84c0.png)

**Comment by alanraju-aot** [comment]
Can you update in, what Virtualization tool are you using?

**Comment by alanraju-aot** [comment]
Also just check the formsflow-ai version, you have mentioned it as 5.0.2.

**Comment by sreehari-aot** [comment]
Your server is also incompatible with mongo:5.
https://github.com/AOT-Technologies/forms-flow-ai/blob/master/deployment/docker/docker-compose.yml#L7
Here you can try out lower versions of the mongo image mongo:4.4.6 or 4.2 should work.
