### ISSUE TITLE
[Question] - Help required with openshift4 deployment

### ISSUE THREAD

**Issue by dinbtechit** [AOT-Technologies/forms-flow-ai#984]
Hi, I am trying to deploy the stack on openshift 4. However, the documentation seems a bit limited. Can you please provide some step-by-step instructions? 

There are no instructions in which order the template should be executed.. I tried to deploy the MongoDB secrets template and an error. Below are the steps.

1.  cd into database
```shell
cd deployment/openshift/Databases
```
2. Updated the `mongo-db_param.yaml` with all default values.
3. Attempted to deploy into the namespace:
```shell
oc process -f openshift/Databases/mongodb-secret.yaml --param-file=mongo-db_param.yaml
```
**output:**
```
error: failed to read input object (not a Template?): resource mapping not found for name: "" namespace: "" from "openshift/Databases/mongodb-secret.yaml": no matches for kind "Template" in version "v1"
ensure CRDs are installed first

```

**Comment by sumesh-aot** [comment]
@dinbtechit Openshift deployment templates are deprecated, please use the helm charts. We will be removing these in next update. I have updated your other ticket on doc update.

**Comment by dinbtechit** [comment]
oh ok. thats good to know. Thank you.
