### ISSUE TITLE
Camunda unable to get access token from Keycloak server

### ISSUE THREAD

**Issue by yhrchan** [AOT-Technologies/forms-flow-ai#99]
### Please provide information about your setup

- formsflow.ai Version: latest code from git repo
- Browser: Edge
- Browser version: 

### Steps to Reproduce

1. Followed steps to install Keycloak server based on the following instructions -> https://github.com/AOT-Technologies/forms-flow-ai/blob/master/forms-flow-idm/keycloak-setup.md and I was able to verify Postman calls to test the forms-flow-bpm access  to get access token from Keycloak server and verified access token in jwt.io website.
2. Followed the steps https://github.com/AOT-Technologies/forms-flow-ai/tree/master/forms-flow-bpm to try and get the Workflow engine running but got the following error while running docker-compose

Note I've filled in the following env variables in .env under forms-flow-bpm folder

## Environment Variables for Keycloak
KEYCLOAK_URL=https://xxxxxx.ngrok.io
KEYCLOAK_URL_REALM=forms-flow-ai
KEYCLOAK_BPM_CLIENTID=forms-flow-bpm
KEYCLOAK_BPM_CLIENTSECRET=[i've copied and pasted the same client secret i've used to verify in Postman here]

### Observed Behaviour

![2021-06-06](https://user-images.githubusercontent.com/3683552/120916447-e96b0180-c666-11eb-8d85-698f8bdc6ff7.png)

### Expected Behaviour

That Camunda could start and I should be able to access it via http://localhost:8000

**Comment by abhilash-aot** [comment]
@yhrchan  There is a new release given ,this should solve your issues . Can you try with the updated installation guide in  documentation .

**Comment by yhrchan** [comment]
Hi @abhilash-aot 

Just git clone v4 and starting to follow the new installation documentations but ran into some issues building the forms-flow-analytics container as shown in the screenshot below.

For Windows,
Run docker-compose -f docker-compose-windows.yml run --rm server create_db to setup database and to create tables.
Run docker-compose -f docker-compose-windows.yml up -d to start.

![2021-06-12](https://user-images.githubusercontent.com/3683552/121772959-1f602800-cb36-11eb-8ad4-c093aa19a485.png)

**Comment by abhilash-aot** [comment]
Hi @yhrchan , 
Thanks for reporting. Seems like the issue is with the system time/docker vm. Can you check the System time / Restart docker and try once. Refer [link](https://askubuntu.com/questions/1059217/getting-release-is-not-valid-yet-while-updating-ubuntu-docker-container). Please let us know if you still run into issue again. We will check deeper into the issue. Thanks.
