### ISSUE TITLE
[Question] - FormsFlow -> Admin -> Internal Server Error

### ISSUE THREAD

**Issue by dinbtechit** [AOT-Technologies/forms-flow-ai#991]
I have deployed formflow-ai using the Helm charts. The apps the be working very well except the "admin" tab shows an `Intenal Server Error`. Any idea what is going on?

![image](https://user-images.githubusercontent.com/17984781/199546745-deee733e-08d3-458f-bd17-11ed9cd7ce8d.png)

**Comment by dinbtechit** [comment]
Initiated a discussion for this. https://github.com/AOT-Technologies/forms-flow-ai/discussions/993

**Comment by sumesh-aot** [comment]
Discussion updated with comment
