### ISSUE TITLE
Pre-fill form

### ISSUE THREAD

**Issue by TriStarGod** [AOT-Technologies/forms-flow-ai#998]
Hi,
This looks like a great project. Is there a way to partially pre-fill forms?
Thanks

**Comment by sumesh-aot** [comment]
@TriStarGod There are ways to do it.
@abhilash-aot Can you provide some details ?

**Comment by abhilash-aot** [comment]
@TriStarGod Yes we can prefill the data in forms . This can we achieved when designing step of the form either of the following ways 

> **Setting a default value  in the form component.** 
![image](https://user-images.githubusercontent.com/61222674/200709569-1fdecf6f-8e42-452c-92e8-251dcb039e51.png)


> **Using Default Calculated Value** 
![image](https://user-images.githubusercontent.com/61222674/200710163-bce33b64-ad5c-40a3-a6d7-c3d7f6ac7a6c.png)
Setting the value with JS: 
![image](https://user-images.githubusercontent.com/61222674/200710052-cbada604-5a83-4557-9ba8-5e0aa7639613.png)
Result on form load for Submission:
![image](https://user-images.githubusercontent.com/61222674/200710532-cf3411c2-49c7-44ec-8998-e61191d5c98e.png)

> With calculated Value in Javascript or adding calling api and using those data to pre-populate the data. Some component like select has default support to take values from api/resources etc .
Select component load option example:
![image](https://user-images.githubusercontent.com/61222674/200710910-a9b924b1-235e-4489-8a42-d432aff98ec1.png)
![image](https://user-images.githubusercontent.com/61222674/200711205-5692b03a-61f4-4b1c-bcc8-4825e66f6292.png)
Loading a table with JS api call:
![image](https://user-images.githubusercontent.com/61222674/200711175-dd2af838-3748-4e24-bc85-bc732efa62cf.png)

> Conditionally pre-populate the value of a field dependent on the value filled or a condition met in another field. 
This can again be controlled with JavaScript

**Comment by sreehari-aot** [comment]
@TriStarGod It is totally possible. Formsflow.ai supports all features of Formio. If you have a look at the third screenshot we can write javascript logic to fetch necessary data and pass it to the form. We have a lot of implementations of such nature.
